services:
  dbtorneig:
    container_name: torneig-DB
    build: ./BD
    #restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - dbtorneig_data:/var/lib/mysql
    networks:
      - torneignet

  apitorneig:
    container_name: torneig-API
    depends_on:
      - dbtorneig
    build: ./Torneig_Mort_Spring
    #restart: on-failure
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{ "spring.datasource.url"  : "jdbc:mysql://dbtorneig/Torneig_demo", "spring.datasource.username" : "$MYSQLDB_USER", "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD", "spring.jpa.hibernate.ddl-auto" : "validate", "spring.jpa.show-sql" : "true" }'
    #stdin_open: true
    #tty: true
    networks:
      - torneignet

  webtorneig:
    container_name: torneig-WEB
    depends_on:
      - apitorneig
    build: ./app_torneig_flutter
    ports:
      - "8080:80"
    networks:
      - torneignet

volumes:
  dbtorneig_data:


networks:
  torneignet:
    driver: bridge
